export const LOAD_ITEMS_UNSOLVED = "LOAD_ITEMS_UNSOLVED";
export const UPDATE_ITEMS_UNSOLVED = "UPDATE_ITEMS_UNSOLVED";
export const LOAD_ITEMS_SOLVED = "LOAD_ITEMS_SOLVED";
export const UPDATE_ITEMS_SOLVED = "UPDATE_ITEMS_SOLVED";
export const LOAD_ITEMS_POPULAR = "LOAD_ITEMS_POPULAR";
export const UPDATE_ITEMS_POPULAR = "UPDATE_ITEMS_POPULAR";
export const LOAD_ITEMS_SEARCHED = "LOAD_ITEMS_SEARCHED";
export const UPDATE_ITEMS_SEARCHED = "UPDATE_ITEMS_SEARCHED";

export const LOAD_SHOW_VISIBLE = "LOAD_SHOW_VISIBLE";
export const UPDATE_SHOW_VISIBLE = "UPDATE_SHOW_VISIBLE";
export const LOAD_SHOW_INVISIBLE = "LOAD_SHOW_INVISIBLE";
export const UPDATE_SHOW_INVISIBLE = "UPDATE_SHOW_INVISIBLE";

export const ADD_ITEM = "ADD_ITEM";

export const UPDATE_REPLY = "UPDATE_REPLY";
export const LOAD_REPLY = "LOAD_REPLY";