export const LOAD_ITEMS_UNSOLVED = "LOAD_ITEMS_UNSOLVED";
export const UPDATE_ITEMS_UNSOLVED = "UPDATE_ITEMS_UNSOLVED";
export const LOAD_ITEMS_SOLVED = "LOAD_ITEMS_SOLVED";
export const UPDATE_ITEMS_SOLVED = "UPDATE_ITEMS_SOLVED";
export const LOAD_ITEMS_POPULAR = "LOAD_ITEMS_POPULAR";
export const UPDATE_ITEMS_POPULAR = "UPDATE_ITEMS_POPULAR";